import type { CSSProperties } from "react";

// Shared style objects for the calendar UI, expressed as DOM inline styles
// (`React.CSSProperties`). Interactive affordances (hover/active cursors,
// focus rings, button base reset) live in `app/globals.css`.

export const colors = {
  primary: "#2563eb",
  primaryDark: "#1d4ed8",
  text: "#111827",
  muted: "#6b7280",
  bg: "#ffffff",
  card: "#f9fafb",
  border: "#e5e7eb",
  booked: "#dbeafe",
  request: "#fef3c7",
  requestText: "#92400e",
  full: "#fee2e2",
  fullText: "#991b1b",
  today: "#ecfdf5",
  past: "#f3f4f6",
  pastText: "#9ca3af",
  danger: "#dc2626",
  success: "#16a34a",
  warn: "#d97706",
};

type Styles = Record<string, CSSProperties>;

export const styles = {
  container: { backgroundColor: colors.bg },
  content: {
    padding: 16,
    display: "flex",
    flexDirection: "column",
    gap: 16,
  },

  // Header
  header: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingTop: 8,
    paddingBottom: 8,
    borderBottom: `1px solid ${colors.border}`,
  },
  h1: { fontSize: 22, fontWeight: 700, color: colors.text, margin: 0 },
  h2: {
    fontSize: 18,
    fontWeight: 600,
    color: colors.text,
    marginTop: 8,
    marginBottom: 8,
  },
  h3: { fontSize: 16, fontWeight: 600, color: colors.text, margin: 0 },

  // Buttons
  btn: {
    paddingTop: 10,
    paddingBottom: 10,
    paddingLeft: 14,
    paddingRight: 14,
    borderRadius: 8,
    backgroundColor: colors.primary,
    color: "#fff",
    fontWeight: 600,
    border: "none",
    cursor: "pointer",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
  },
  btnText: { color: "#fff", fontWeight: 600 },
  btnSecondary: { backgroundColor: colors.muted },
  btnDanger: { backgroundColor: colors.danger },
  btnConfirm: { backgroundColor: colors.success },
  btnNav: {
    backgroundColor: colors.card,
    color: colors.text,
    paddingTop: 8,
    paddingBottom: 8,
    paddingLeft: 12,
    paddingRight: 12,
  },
  btnNavText: { color: colors.text, fontWeight: 600 },
  btnDisabled: { opacity: 0.5, cursor: "not-allowed" },

  // Calendar grid
  calendarControls: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingTop: 8,
    paddingBottom: 8,
  },
  currentMonth: { fontSize: 18, fontWeight: 700, color: colors.text },
  weekRow: { display: "flex", flexDirection: "row" },
  weekCell: {
    flex: 1,
    textAlign: "center",
    paddingTop: 6,
    paddingBottom: 6,
  },
  weekCellText: { color: colors.muted, fontWeight: 600, fontSize: 12 },
  grid: {
    display: "flex",
    flexDirection: "row",
    flexWrap: "wrap",
    borderTop: `1px solid ${colors.border}`,
    borderLeft: `1px solid ${colors.border}`,
    borderRadius: 6,
    overflow: "hidden",
  },
  cell: {
    width: "14.2857%",
    boxSizing: "border-box",
    minHeight: 88,
    borderRight: `1px solid ${colors.border}`,
    borderBottom: `1px solid ${colors.border}`,
    padding: 4,
    backgroundColor: colors.bg,
    textAlign: "left",
    cursor: "pointer",
    display: "block",
  },
  cellEmpty: { backgroundColor: colors.card },
  cellToday: { backgroundColor: colors.today },
  cellBooked: { backgroundColor: colors.booked },
  cellFull: { backgroundColor: colors.full },
  cellPast: { backgroundColor: colors.past },
  dayNumber: { fontSize: 11, fontWeight: 600, color: colors.text },
  dayNumberPast: { color: colors.pastText },
  bookingMini: {
    backgroundColor: colors.primary,
    paddingLeft: 4,
    paddingRight: 4,
    paddingTop: 2,
    paddingBottom: 2,
    borderRadius: 3,
    marginTop: 2,
  },
  bookingMiniRequest: { backgroundColor: colors.request },
  bookingMiniText: {
    color: "#fff",
    fontSize: 10,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  bookingMiniRequestText: {
    color: colors.requestText,
    fontSize: 10,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  bookingMore: { fontSize: 10, color: colors.muted, marginTop: 2 },
  capacityLine: { fontSize: 10, color: colors.muted, marginTop: 2 },

  // Bookings list
  bookingItem: {
    padding: 12,
    borderRadius: 8,
    backgroundColor: colors.card,
    display: "flex",
    flexDirection: "column",
    gap: 6,
  },
  bookingItemRequest: { backgroundColor: colors.request },
  bookingDate: { color: colors.muted, fontSize: 13 },
  bookingDetails: { color: colors.text },
  bookingName: { fontWeight: 700, color: colors.text },
  bookingComment: { color: colors.muted, fontStyle: "italic" },
  badge: {
    alignSelf: "flex-start",
    backgroundColor: colors.warn,
    color: "#fff",
    paddingLeft: 6,
    paddingRight: 6,
    paddingTop: 2,
    paddingBottom: 2,
    borderRadius: 4,
  },
  badgeText: { color: "#fff", fontSize: 10, fontWeight: 700 },
  actionsRow: { display: "flex", flexDirection: "row", gap: 8, flexWrap: "wrap" },

  // Modal
  modalBackdrop: {
    position: "fixed",
    inset: 0,
    backgroundColor: "rgba(0,0,0,0.5)",
    display: "flex",
    justifyContent: "center",
    alignItems: "flex-start",
    padding: 16,
    overflowY: "auto",
    zIndex: 1000,
  },
  modalContent: {
    backgroundColor: colors.bg,
    borderRadius: 12,
    padding: 16,
    width: "100%",
    maxWidth: 920,
    margin: "auto",
    maxHeight: "90%",
    overflowY: "auto",
    display: "flex",
    flexDirection: "column",
    gap: 12,
  },
  formGroup: { display: "flex", flexDirection: "column", gap: 6 },
  label: { fontSize: 14, color: colors.text, fontWeight: 500 },
  input: {
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: colors.border,
    borderRadius: 8,
    paddingLeft: 10,
    paddingRight: 10,
    paddingTop: 8,
    paddingBottom: 8,
    fontSize: 14,
    color: colors.text,
    backgroundColor: colors.bg,
    boxSizing: "border-box",
    width: "100%",
    fontFamily: "inherit",
  },
  inputError: { borderColor: colors.danger },
  textarea: { minHeight: 60, resize: "vertical" },
  checkboxRow: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    background: "none",
    border: "none",
    padding: 0,
    cursor: "pointer",
    textAlign: "left",
  },

  capacityInfo: {
    padding: 10,
    backgroundColor: colors.card,
    borderRadius: 6,
    display: "flex",
    flexDirection: "column",
    gap: 4,
  },
  error: { color: colors.danger },
  info: { color: colors.muted },
  muted: { color: colors.muted },
  bold: { fontWeight: 700 },

  // FAB
  fab: {
    position: "fixed",
    right: 20,
    bottom: 20,
    backgroundColor: colors.primary,
    color: "#fff",
    borderRadius: 28,
    paddingTop: 12,
    paddingBottom: 12,
    paddingLeft: 18,
    paddingRight: 18,
    display: "flex",
    flexDirection: "row",
    gap: 6,
    alignItems: "center",
    border: "none",
    cursor: "pointer",
    boxShadow: "0 2px 4px rgba(0,0,0,0.2)",
  },
  fabPlus: { color: "#fff", fontSize: 20, fontWeight: 700 },
  fabText: { color: "#fff", fontWeight: 700, fontSize: 16 },

  modalActions: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "flex-end",
    gap: 8,
  },
} satisfies Styles;
